{
 "title": "Assertions",
 "tags": [ "saafe" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(ALERTS{alertstate=\"firing\"},job)"
    }
   },
   { "name": "category", "query": { "query": "label_values(saafe_category)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Assertions Over Time",
   "type": "timeseries",
   "description": "Assertions over time by severity.",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (saafe_severity) (ALERTS{job=~\"$job\", saafe_severity=\"critical\", alertstate=\"firing\", saafe_category=~\"$category\"})",
     "legendFormat": "{{saafe_severity}}"
    },
    {
     "expr": "sum by (saafe_severity) (ALERTS{job=~\"$job\", saafe_severity=\"warning\", alertstate=\"firing\", saafe_category=~\"$category\"})",
     "legendFormat": "{{saafe_severity}}"
    },
    {
     "expr": "sum by (saafe_severity) (ALERTS{job=~\"$job\", saafe_severity=\"info\", alertstate=\"firing\", saafe_category=~\"$category\"})",
     "legendFormat": "{{saafe_severity}}"
    }
   ]
  },
  {
   "title": "Scored Jobs",
   "type": "table",
   "description": "A ranked list of scored jobs with active assertions. The ranking is affected by the number of active assertions and their duration, weighted by severity. Use it to focus attention and narrow down the list of jobs.",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum by (job, saafe_severity) (count_over_time(ALERTS{job=~\"$job\", saafe_category=~\"$category\",alertstate=\"firing\"}[$__range])) * on (saafe_severity) group_left saafe:scoring:weight",
     "legendFormat": "{{job}} - {{saafe_category}}"
    }
   ]
  },
  { "title": "Timeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "$job",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "repeat": "job",
   "targets": [
    {
     "expr": "sum by (job, alertname, saafe_severity) (ALERTS{job=~\"$job\", saafe_category=~\"$category\", saafe_severity=\"info\",alertstate=\"firing\"})",
     "legendFormat": "{{alertname}}"
    },
    {
     "expr": "sum by (job, alertname, saafe_severity) (ALERTS{job=~\"$job\", saafe_category=~\"$category\", saafe_severity=\"warning\",alertstate=\"firing\"})",
     "legendFormat": "{{alertname}}"
    },
    {
     "expr": "sum by (job, alertname, saafe_severity) (ALERTS{job=~\"$job\", saafe_category=~\"$category\", saafe_severity=\"critical\",alertstate=\"firing\"})",
     "legendFormat": "{{alertname}}"
    }
   ]
  }
 ]
}