{
 "title": "Demo Dashboard",
 "tags": [
  "demo",
  "saafe"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "duration_milliseconds_bucket" } },
   {
    "name": "job",
    "query": {
     "query": "label_values({service_name=\"$service\"},job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Spanmetrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency for ${service}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(duration_milliseconds_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile999"
    }
   ]
  },
  {
   "title": "Error Rate for ${service} by span name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": " sum by (span_name) (rate(calls_total{status_code=\"STATUS_CODE_ERROR\", service_name=\"${service}\"}[$__rate_interval]))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  {
   "title": "Requests Rate for ${service} by span name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (span_name) (rate(duration_milliseconds_count{service_name=\"${service}\"}[$__rate_interval]))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  {
   "title": "Assertions",
   "type": "state-timeline",
   "description": "This is an example on how assertions can be incorporated into a service overview dashboard.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum by (job, alertname, saafe_severity) (ALERTS{job=~\"$job\", saafe_severity=\"info\",alertstate=\"firing\"})",
     "legendFormat": "{{alertname}}"
    },
    {
     "expr": "sum by (job, alertname, saafe_severity) (ALERTS{job=~\"$job\", saafe_severity=\"warning\",alertstate=\"firing\"})",
     "legendFormat": "{{alertname}}"
    },
    {
     "expr": "sum by (job, alertname, saafe_severity) (ALERTS{job=~\"$job\", saafe_severity=\"critical\",alertstate=\"firing\"})",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Python services (CPU%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_runtime_cpython_cpu_time_seconds_total{type=~\"system\"}[$__rate_interval])*100",
     "legendFormat": "{{job}} ({{type}})"
    },
    {
     "expr": "rate(process_runtime_cpython_cpu_time_seconds_total{type=~\"user\"}[$__rate_interval])*100",
     "legendFormat": "{{job}} ({{type}})"
    }
   ]
  },
  {
   "title": "Python services (Memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_cpython_memory_bytes{type=\"rss\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Quote Service batch span processor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(otel_trace_span_processor_spans{job=\"quoteservice\"}[2m])*120",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Recommendations Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "rate(app_recommendations_counter_total{recommendation_type=\"catalog\"}[$__rate_interval])",
     "legendFormat": "recommendations"
    }
   ]
  }
 ]
}